### ISSUE TITLE
[publisering] PDF-filnavnet bør gjenspeile spesifikasjonens navn

### ISSUE THREAD

**Issue by jimjyang** [Informasjonsforvaltning/termlosen#11]
Navnet til PDF-filen som kan lastes ned er nå "document.pdf". 

Ønsker å ha et filnavn som gjenspeile spesifikasjonens navn, f.eks. repo-navnet (som også brukes i URLen til den gjeldende versjonen på data.norge.no).

**Comment by stigbd** [comment]
Fiksa i 592847663a7a60a714b6b288540210bacb3686c7

**Comment by jimjyang** [comment]
Fiksa
